name: WorldGuardFix
version: 1.7.5-dev-1
description: WorldGuard Fix for Minecraft 1.12.1
author: Kakifrucht, Steven M.
website: https://halfminer.de

main: de.halfminer.worldguardfix.WorldGuardFix
depend: [WorldGuard]

commands:
  worldguardfix:
    description: Generate and reload the config
    aliases: [wgf]

permissions:
  worldguardfix:
    default: op
    description: Access to /worldguardfix
